name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: input
    id: bun-version
    attributes:
      label: Bun version
      description: "Output of `bun --version`"
      placeholder: "1.2.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: "e.g. macOS 15.3, Ubuntu 24.04, Windows 11"
      placeholder: "macOS 15.3"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: "Minimal steps to reproduce the issue"
      placeholder: |
        1. Run `todoist ...`
        2. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: "What you expected to happen"

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: "What actually happened"
    validations:
      required: true
